spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/tb_logistica
    driver-class-name: com.mysql.jdbc.Driver
  sql:
    init:
      mode: always
  kafka:
    consumer:
      bootstrap-servers: localhost:29092
      group-id: teste
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
topic:
  order-logistic: order-logistic

  threads:
    virtual:
      enabled: true
server:
  compression:
    enabled: 'true'
  port: 8006
  forward-headers-strategy: native